language: scala
jdk:
    - oraclejdk8
    - oraclejdk7
script:
    # Build a config file
    - echo "baseurl=https://sandbox.demo.socrata.com" > src/test/resources/TestConfig.properties
    - echo "token=${SOCRATA_APP_TOKEN}"  >> src/test/resources/TestConfig.properties
    - echo "username=${SOCRATA_USERNAME}"  >> src/test/resources/TestConfig.properties
    - echo "password=${SOCRATA_PASSWORD}"  >> src/test/resources/TestConfig.properties

    # Force TLS 1.1 or 1.2 for tests
    - sbt -Ddeployment.security.SSLv2Hello=false -Ddeployment.security.SSLv3=false -Ddeployment.security.TLSv1=false -Ddeployment.security.TLSv1.1=true -Ddeployment.security.TLSv1.2=true -Dhttps.protocols=TLSv1.1,TLSv1.2 test
